# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import preprocessing_pb2 as preprocessing__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in preprocessing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PreprocessingServiceStub(object):
    """Serviço de pré-processamento invocado pelo Gateway via RPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PreprocessData = channel.unary_unary(
                '/preprocessing.PreprocessingService/PreprocessData',
                request_serializer=preprocessing__pb2.RawReading.SerializeToString,
                response_deserializer=preprocessing__pb2.ProcessedReading.FromString,
                _registered_method=True)
        self.ConvertFormat = channel.unary_unary(
                '/preprocessing.PreprocessingService/ConvertFormat',
                request_serializer=preprocessing__pb2.FormatRequest.SerializeToString,
                response_deserializer=preprocessing__pb2.FormatResponse.FromString,
                _registered_method=True)


class PreprocessingServiceServicer(object):
    """Serviço de pré-processamento invocado pelo Gateway via RPC
    """

    def PreprocessData(self, request, context):
        """Pré-processa uma leitura bruta de sensor (normalização, qualidade, outlier)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertFormat(self, request, context):
        """Converte dados entre formatos (JSON, XML, CSV) para JSON normalizado
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreprocessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PreprocessData': grpc.unary_unary_rpc_method_handler(
                    servicer.PreprocessData,
                    request_deserializer=preprocessing__pb2.RawReading.FromString,
                    response_serializer=preprocessing__pb2.ProcessedReading.SerializeToString,
            ),
            'ConvertFormat': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertFormat,
                    request_deserializer=preprocessing__pb2.FormatRequest.FromString,
                    response_serializer=preprocessing__pb2.FormatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'preprocessing.PreprocessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('preprocessing.PreprocessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreprocessingService(object):
    """Serviço de pré-processamento invocado pelo Gateway via RPC
    """

    @staticmethod
    def PreprocessData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/preprocessing.PreprocessingService/PreprocessData',
            preprocessing__pb2.RawReading.SerializeToString,
            preprocessing__pb2.ProcessedReading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertFormat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/preprocessing.PreprocessingService/ConvertFormat',
            preprocessing__pb2.FormatRequest.SerializeToString,
            preprocessing__pb2.FormatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
