# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: preprocessing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'preprocessing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13preprocessing.proto\x12\rpreprocessing\"t\n\nRawReading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\t\x12\x13\n\x0braw_payload\x18\x06 \x01(\t\"\xdb\x01\n\x10ProcessedReading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\x18\n\x10normalized_value\x18\x03 \x01(\x01\x12\x17\n\x0fnormalized_unit\x18\x04 \x01(\t\x12\x0f\n\x07quality\x18\x05 \x01(\t\x12\x12\n\nis_outlier\x18\x06 \x01(\x08\x12\x0f\n\x07z_score\x18\x07 \x01(\x01\x12\x11\n\ttimestamp\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\x12\x15\n\rerror_message\x18\n \x01(\t\"8\n\rFormatRequest\x12\x10\n\x08raw_data\x18\x01 \x01(\t\x12\x15\n\rsource_format\x18\x02 \x01(\t\"Q\n\x0e\x46ormatResponse\x12\x17\n\x0fnormalized_json\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xb2\x01\n\x14PreprocessingService\x12L\n\x0ePreprocessData\x12\x19.preprocessing.RawReading\x1a\x1f.preprocessing.ProcessedReading\x12L\n\rConvertFormat\x12\x1c.preprocessing.FormatRequest\x1a\x1d.preprocessing.FormatResponseB\x17\xaa\x02\x14PreprocessingServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'preprocessing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\024PreprocessingService'
  _globals['_RAWREADING']._serialized_start=38
  _globals['_RAWREADING']._serialized_end=154
  _globals['_PROCESSEDREADING']._serialized_start=157
  _globals['_PROCESSEDREADING']._serialized_end=376
  _globals['_FORMATREQUEST']._serialized_start=378
  _globals['_FORMATREQUEST']._serialized_end=434
  _globals['_FORMATRESPONSE']._serialized_start=436
  _globals['_FORMATRESPONSE']._serialized_end=517
  _globals['_PREPROCESSINGSERVICE']._serialized_start=520
  _globals['_PREPROCESSINGSERVICE']._serialized_end=698
# @@protoc_insertion_point(module_scope)
